#!/usr/bin/env bash
# Build the LOADED user program as its own static no-pie ELF64, then embed its
# bytes into user_elf.h (an xxd-style C array) so the kernel can put the whole
# image into the proven content-addressed store at boot (there is no filesystem).
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
CL="${CVSASX_CLANG:?set CVSASX_CLANG to a freestanding x86-64 clang}"
LD="${CVSASX_LLD:?set CVSASX_LLD to ld.lld}"
OD="${CVSASX_OBJDUMP:?set CVSASX_OBJDUMP to llvm-objdump}"

"$CL" --target=x86_64-unknown-none-elf -ffreestanding -nostdlib -fno-pic -fno-pie \
      -c "$HERE/user_prog.S" -o "/tmp/user_prog.o"
"$LD" -m elf_x86_64 -static -no-pie -T "$HERE/user_prog.ld" -o "$HERE/user_prog.elf" "/tmp/user_prog.o"

echo "=== user_prog.elf size: $(stat -c%s "$HERE/user_prog.elf") bytes ==="
"$OD" --all-headers "$HERE/user_prog.elf" 2>/dev/null | grep -A4 -iE 'entry|LOAD|filesz' | head -40 || true

# Embed bytes as a C header. xxd -i if present, else a portable od alternative.
SZ=$(stat -c%s "$HERE/user_prog.elf")
{
  echo "/* AUTO-GENERATED by user_build.sh - bytes of kernel/user_prog.elf (the loaded ring-3 ELF)."
  echo " * The kernel embeds these (no filesystem at boot), cvsasx_store_put()s the whole image,"
  echo " * then parses+materializes its PT_LOAD segments by BLAKE3 hash. Do not hand-edit. */"
  echo "static const unsigned char user_prog_elf[] = {"
  od -An -v -tx1 "$HERE/user_prog.elf" | sed 's/[0-9a-f]\{2\}/0x&,/g'
  echo "};"
  echo "static const unsigned long user_prog_elf_len = ${SZ}UL;"
} > "$HERE/user_elf.h"
echo "=== wrote user_elf.h (${SZ} bytes embedded) ==="
